name: Release

on:
  release:
    types: [released]

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.arch }} binary
    runs-on: ${{ matrix.runner }}   
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64-unknown-linux-gnu
            os: linux
            runner: ubuntu-latest
            file: aerp-linux-x86_64
            build-step: |
              cargo build --release --target x86_64-unknown-linux-gnu
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust with dtolnay/toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.86
          target: ${{ matrix.arch }}

      - name: Install Linux dependencies
        if: matrix.os == 'linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build
        run: ${{ matrix.build-step }}
    